#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_neomake = false
    enable_ale = true
    filemanager = "nerdtree"
    disabled_plugins = ['phpfold.vim']
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    default_indent = 4
    sidebar_direction = 'left'
    autocomplete_method = "coc"

#[[custom_plugins]]
#    name = "autozimu/LanguageClient-neovim"
#    rev = "next"
#    build = "bash install.sh"
#    on_ft = "php"
#[[custom_plugins]]
#    name = "TysonAndre/LanguageServer-phan-neovim"
#    on_ft = "php"
#    build = "composer update"
[[custom_plugins]]
    name = "skywind3000/asyncrun.vim"
[[custom_plugins]]
    name = "eshion/vim-sync"
[[custom_plugins]]
    name = "arnaud-lb/vim-php-namespace"
    on_ft = "php"
[[custom_plugins]]
    name = "ludovicchabant/vim-gutentags"
    on_ft = "php"
[[custom_plugins]]
    name = "907th/vim-auto-save"
[[custom_plugins]]
    name = "roman/golden-ratio"
[[custom_plugins]]
    name = "itchyny/vim-cursorword"
[[custom_plugins]]
    name = "KabbAmine/zeavim.vim"
[[custom_plugins]]
    name = "superevilmegaco/AutoRemoteSync.nvim"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'

[[layers]]
name = 'git'

[[layers]]
name = "lang#javascript"
enable_flow_syntax=true

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#c"

[[layers]]
  name = "lsp"
  filetypes = [
    "javascript",
  ]

[[layers]]
  name = "fzf"

[[layers]]
  name = "colorscheme"

